### ISSUE TITLE
2021-01-03更新 增加 CUSTOM_SHELL_FILE 参数配置执行自定义shell脚本

### ISSUE THREAD

**Issue by ekonoob** [iouAkira/someDockerfile#10]
大佬你好，自定义是在docker-compose.yml里添加CUSTOM_SHELL_FILE=https://raw.githubusercontent.com/iouAkira/someDockerfile/master/jd_scripts/shell_script_mod.sh
参数吗？？

**Comment by iouAkira** [comment]
> 大佬你好，自定义是在docker-compose.yml里添加CUSTOM_SHELL_FILE=https://raw.githubusercontent.com/iouAkira/someDockerfile/master/jd_scripts/shell_script_mod.sh
> 参数吗？？

那边说明写的很清楚了，在yml加环境变量配置，另外不要在这边提issues.
