### ISSUE TITLE
新的jd_scripts部署后启动出错

### ISSUE THREAD

**Issue by fengmikaelson** [iouAkira/someDockerfile#13]
![微信截图_20210116131851](https://user-images.githubusercontent.com/10394327/104797956-78cd6080-57fd-11eb-8297-993bdf368026.png)

{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "",
   "cpu_priority" : 0,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "CDN_JD_DAILYBONUS",
         "value" : "true"
      },
      {
         "key" : "JD_COOKIE",
         "value" : "pt_key=xxx;pt_pin=xxx;&pt_key=111;pt_pin=111;"
      },
      {
         "key" : "BARK_PUSH",
         "value" : "https://api.day.app/xxx"
      },
      {
         "key" : "BARK_SOUND",
         "value" : "https://api.day.app/xxx/推送铃声?sound=healthnotification"
      },
      {
         "key" : "PLANT_BEAN_SHARECODES",
         "value" : ""
      },
      {
         "key" : "FRUITSHARECODES",
         "value" : ""
      },
      {
         "key" : "PETSHARECODES",
         "value" : ""
      },
      {
         "key" : "SUPERMARKET_SHARECODES",
         "value" : ""
      },
      {
         "key" : "CRONTAB_LIST_FILE",
         "value" : "crontab_list.sh"
      }
   ],
   "exporting" : false,
   "id" : "18af38bc0ac37a40e4b9608a86fef56c464577cc160bbdddec90155284fcf4e5",
   "image" : "akyakya/jd_scripts",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "jd_scripts",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "default",
   "port_bindings" : [],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/jd_scripts/logs",
         "mount_point" : "/scripts/logs",
         "type" : "rw"
      }
   ]
}

一直报启动错误。重新拿一份新的脚本填写，导入也还是这样。。。

**Comment by iouAkira** [comment]
在调整测试

**Comment by fengmikaelson** [comment]
> 在调整测试

好的，不好意思，是我心急了。。收到更新提醒，马上去下载更新了。。。

**Comment by iouAkira** [comment]
> > 在调整测试
> 
> 好的，不好意思，是我心急了。。收到更新提醒，马上去下载更新了。。。

已经更新可以用了，但是后续不再提供使用咨询和帮助，因为此镜像偏向自用，shell脚本用的都是我自己仓库维护方便修改调整，建议更换其他有详细使用教程的镜像使用

**Comment by fengmikaelson** [comment]
> > > 在调整测试
> > 
> > 
> > 好的，不好意思，是我心急了。。收到更新提醒，马上去下载更新了。。。
> 
> 已经更新可以用了，但是后续不再提供使用咨询和帮助，因为此镜像偏向自用，shell脚本用的都是我自己仓库维护方便修改调整，建议更换其他有详细使用教程的镜像使用

了解。多谢！！！

**Comment by fengmikaelson** [comment]
> > > 在调整测试
> > 
> > 
> > 好的，不好意思，是我心急了。。收到更新提醒，马上去下载更新了。。。
> 
> 已经更新可以用了，但是后续不再提供使用咨询和帮助，因为此镜像偏向自用，shell脚本用的都是我自己仓库维护方便修改调整，建议更换其他有详细使用教程的镜像使用

大佬，我再问下，你这个docker有控制面板功能吗？我把web page改为true后，映射了端口似乎不起作用。
