### ISSUE TITLE
这两个npm install 好像没用

### ISSUE THREAD

**Issue by AboutCXJ** [iouAkira/someDockerfile#14]
路径还是在lxk的仓库，装的都是lxk的以来，丝毫没装shylock的依赖
<img width="547" alt="截屏2021-01-21 上午11 47 04" src="https://user-images.githubusercontent.com/19811825/105277489-780e4300-5bde-11eb-9272-fe0424c2325e.png">

**Comment by AboutCXJ** [comment]
应该合并两个仓库的package.json再 npm install

**Comment by AboutCXJ** [comment]
https://www.npmjs.com/package/package-merge

**Comment by iouAkira** [comment]
> 应该合并两个仓库的package.json再 npm install

无所谓的，这本没用的 可以删了我是把脚本都丢到了 scripts下面执行的
