### ISSUE TITLE
env的$JD_COOKIE写入文件错误

### ISSUE THREAD

**Issue by xiangtailiang** [iouAkira/someDockerfile#15]
https://github.com/iouAkira/someDockerfile/blob/ec296527e5151d83266ecc470f8255fba618a7b4/dd_scripts/shell_default_script.sh#L121

这里写错了，把文件名写入了cookies.list中，应该改为：
echo "$JD_COOKIE" | sed "s/\( &\|&\)/\\n/g" >"$COOKIE_LIST"

**Comment by xiangtailiang** [comment]
另外请教一个问题，cookies.list是什么时候被读取的，没有配置spnode应该不会使用的吧？
那为什么如果cookies.list写错了，会导致账号识别失败呢？会提示账号为null

**Comment by iouAkira** [comment]
> https://github.com/iouAkira/someDockerfile/blob/ec296527e5151d83266ecc470f8255fba618a7b4/dd_scripts/shell_default_script.sh#L121
> 
> 这里写错了，把文件名写入了cookies.list中，应该改为：
> echo "$JD_COOKIE" | sed "s/( &|&)/\n/g" >"$COOKIE_LIST"

提醒我了，现在这个没啥用了，不兼容以前配置，现在要使用的话需要自己建对应文件结构目录了。

> 另外请教一个问题，cookies.list是什么时候被读取的，没有配置spnode应该不会使用的吧？
> 那为什么如果cookies.list写错了，会导致账号识别失败呢？会提示账号为null

spnode命令里面读取
现在镜像里面包含了spnode 要使用cookies.list 就需要使用spnode执行对应的脚本，使用node 执行只能读取系统里面的环境变量。

**Comment by xiangtailiang** [comment]
> > https://github.com/iouAkira/someDockerfile/blob/ec296527e5151d83266ecc470f8255fba618a7b4/dd_scripts/shell_default_script.sh#L121
> > 
> > 这里写错了，把文件名写入了cookies.list中，应该改为：
> > echo "$JD_COOKIE" | sed "s/( &|&)/\n/g" >"$COOKIE_LIST"
> 
> 提醒我了，现在这个没啥用了，不兼容以前配置，现在要使用的话需要自己建对应文件结构目录了。
> 
> > 另外请教一个问题，cookies.list是什么时候被读取的，没有配置spnode应该不会使用的吧？
> > 那为什么如果cookies.list写错了，会导致账号识别失败呢？会提示账号为null
> 
> spnode命令里面读取
> 现在镜像里面包含了spnode 要使用cookies.list 就需要使用spnode执行对应的脚本，使用node 执行只能读取系统里面的环境变量。

你说现在这个不用了？是有新的docker镜像吗？

**Comment by iouAkira** [comment]
> > > https://github.com/iouAkira/someDockerfile/blob/ec296527e5151d83266ecc470f8255fba618a7b4/dd_scripts/shell_default_script.sh#L121
> > > 
> > > 这里写错了，把文件名写入了cookies.list中，应该改为：
> > > echo "$JD_COOKIE" | sed "s/( &|&)/\n/g" >"$COOKIE_LIST"
> > 
> > 
> > 提醒我了，现在这个没啥用了，不兼容以前配置，现在要使用的话需要自己建对应文件结构目录了。
> > > 另外请教一个问题，cookies.list是什么时候被读取的，没有配置spnode应该不会使用的吧？
> > > 那为什么如果cookies.list写错了，会导致账号识别失败呢？会提示账号为null
> > 
> > 
> > spnode命令里面读取
> > 现在镜像里面包含了spnode 要使用cookies.list 就需要使用spnode执行对应的脚本，使用node 执行只能读取系统里面的环境变量。
> 
> 你说现在这个不用了？是有新的docker镜像吗？

参考新的readme，没有存在的必要了。
