### ISSUE TITLE
arm32运行报错求助

### ISSUE THREAD

**Issue by xC9zzzzz** [iouAkira/someDockerfile#16]
错误代码
`routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330::statem_clnt.c:1913:`
`3069703056:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:`
`3069703056:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:`

docker命令可以通过docker run --security-opt seccomp:unconfined xxxxx 解决
请问在docker-compose上有没有什么办法解决呢

**Comment by iouAkira** [comment]
https://stackoverflow.com/questions/46053672/set-secomp-to-unconfined-in-docker-compose
看下这里,我没这设备没法给你测试
