### ISSUE TITLE
容器启动后无法进入bash

### ISSUE THREAD

**Issue by amountnothing** [iouAkira/someDockerfile#18]
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown

**Comment by xpigm** [comment]
不知道你用的哪个容器，默认情况下基于alpine的镜像是没有bash的，可以改成 `docker exec -it xxx /bin/sh`

**Comment by amountnothing** [comment]
虽然最后用其他方法解决了我的问题，不过还是非常感谢
