### ISSUE TITLE
efb V2 

### ISSUE THREAD

**Issue by fucao** [iouAkira/someDockerfile#19]
1. telegram里都是公众号的推送了，接收不到消息，更换其他的efbv2后，可以收到消息；
![image](https://user-images.githubusercontent.com/15061002/136651503-6817d9fc-d2c0-48d3-b64e-d55657980bfe.png)

2. 转发到channel里的内容跟其他的efb是不一样的，导致rsshub不能正常抓取。就像下图这样：
![image](https://user-images.githubusercontent.com/15061002/136651485-b478c1a4-3a13-4061-8dc2-1dc55220b100.png)

**Comment by iouAkira** [comment]
> 1. telegram里都是公众号的推送了，接收不到消息，更换其他的efbv2后，可以收到消息；
>    ![image](https://user-images.githubusercontent.com/15061002/136651503-6817d9fc-d2c0-48d3-b64e-d55657980bfe.png)
> 2. 转发到channel里的内容跟其他的efb是不一样的，导致rsshub不能正常抓取。就像下图这样：
>    ![image](https://user-images.githubusercontent.com/15061002/136651485-b478c1a4-3a13-4061-8dc2-1dc55220b100.png)

1。这个怎么说呢，收不到消息的问题，只能说是微信的玄学问题，目前我知道的这个景象的10多个用户的是使用正常的

**Comment by Wpenga** [comment]
cust.sh.脚本是怎样的

**Comment by fucao** [comment]
不知道咋弄
