### ISSUE TITLE
由于部分参数问题，导致喜马拉雅无法开启刷时长

### ISSUE THREAD

**Issue by Aaron-lv** [iouAkira/someDockerfile#4]
由于原作者脚本中未定义，XMLY_ACCUMULATE_TIME = os.environ["XMLY_ACCUMULATE_TIME"]，所以Docker容器构建代码中 sed -i 's/if\ XMLY_ACCUMULATE_TIME/if\ os.environ["XMLY_ACCUMULATE_TIME"]/g' /xmly_speed/xmly_speed.py \   修改参数无效，由于在构建代码中将XMLY_ACCUMULATE_TIME 定义为0，导致无法开启刷时长

**Comment by iouAkira** [comment]
> 由于原作者脚本中未定义，XMLY_ACCUMULATE_TIME = os.environ["XMLY_ACCUMULATE_TIME"]，所以Docker容器构建代码中 sed -i 's/if\ XMLY_ACCUMULATE_TIME/if\ os.environ["XMLY_ACCUMULATE_TIME"]/g' /xmly_speed/xmly_speed.py \ 修改参数无效，由于在构建代码中将XMLY_ACCUMULATE_TIME定义为0，导致无法开启刷时长

因为默认刷时长很多都异常了，所以改了构建的时候改了；readme里说了，需要刷时长的在docker-compose.yml里面配置XMLY_ACCUMULATE_TIME=1，难道是配置了也不生效吗？

**Comment by iouAkira** [comment]
我回去再测测看

**Comment by Aaron-lv** [comment]
是的，配置了也无法开启刷时长。

**Comment by iouAkira** [comment]
> 是的，配置了也无法开启刷时长。

好的，我等下看下，谢谢反馈

**Comment by iouAkira** [comment]
> 是的，配置了也无法开启刷时长。

问题已经修复，需要更新镜像。~因为环境变量取到类型是`string`所以 `==1`判断永远都是`false`，就不会上传时长~

**Comment by Aaron-lv** [comment]
好的，感谢
