### ISSUE TITLE
关于喜马拉雅Telegram推送的问题

### ISSUE THREAD

**Issue by Aaron-lv** [iouAkira/someDockerfile#5]
喜马拉雅Telegram不推送，企鹅阅读推送正常，观察两天都未推送，未找到问题所在。。

**Comment by Aaron-lv** [comment]
脚本执行日志提示，Telegram推送打开，实际是未收到推送的。

**Comment by iouAkira** [comment]
原仓库 [_代码_](https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.py#L1033) 判断可能有点问题，因为`docker`执行没有延迟的话30分的时候执行完了,这判断可能就是`false`不推送，我也在考虑怎么调整。如果`fork`一份我自己改了，镜像改为使用 我`fork`的话，就是每次主库有更新，我需要手动解决冲突合并; 构建的时候，`sed` 改的话就有要换东西有点多😂，也比较烦。

**Comment by Aaron-lv** [comment]
[代码](https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.py#L1033) 判断可以修改为>=，实测可以收到推送了

**Comment by iouAkira** [comment]
> [代码](https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.py#L1033) 判断可以修改为>=，实测可以收到推送了

我是想加自定义通知时间。另外准备加一个`docker`提醒更新的功能，周末的时候一块改进去吧。

**Comment by Aaron-lv** [comment]
_[代码](https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.py#L59)_喜马拉雅这里是可以调整时间，写成env应该可以实现，感谢
